name: takeawaybill
channels:
  - defaults
  - conda-forge
dependencies:
  # Python
  - python=3.11
  
  # Data Processing
  - pandas=2.1.3
  - numpy
  
  # HTTP & Networking
  - requests=2.31.0
  
  # Frontend - Streamlit
  - streamlit=1.31.1
  
  # Utilities
  - pip-tools
  - pip
  - ipython
  - ipdb
  - pytest
  - pip:
    - pyjwt==2.8.0
    - cloudscraper==1.2.71
    - python-dotenv==1.0.0
